/*
 * The EBI Search: RESTful Web services
 * This is an API documentation for [EBI Search](https://www.ebi.ac.uk/ebisearch) RESTful Web services.
 *
 * The version of the OpenAPI document: all
 * Contact: www-prod@ebi.ac.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.dissco.digitisers.clients.ebi.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import eu.dissco.digitisers.clients.ebi.openapi.model.WSFieldInfo;
import eu.dissco.digitisers.clients.ebi.openapi.model.WSIndexInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WSDomain
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T16:03:02.863Z[GMT]")
public class WSDomain {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_HIT_COUNT = "hitCount";
  @SerializedName(SERIALIZED_NAME_HIT_COUNT)
  private Long hitCount;

  public static final String SERIALIZED_NAME_INDEX_INFOS = "indexInfos";
  @SerializedName(SERIALIZED_NAME_INDEX_INFOS)
  private List<WSIndexInfo> indexInfos = null;

  public static final String SERIALIZED_NAME_FIELD_INFOS = "fieldInfos";
  @SerializedName(SERIALIZED_NAME_FIELD_INFOS)
  private List<WSFieldInfo> fieldInfos = null;

  public static final String SERIALIZED_NAME_SUBDOMAINS = "subdomains";
  @SerializedName(SERIALIZED_NAME_SUBDOMAINS)
  private List<WSDomain> subdomains = null;

  public static final String SERIALIZED_NAME_REFERENCE_ENTRY_COUNT = "referenceEntryCount";
  @SerializedName(SERIALIZED_NAME_REFERENCE_ENTRY_COUNT)
  private Long referenceEntryCount;


  public WSDomain id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public WSDomain name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public WSDomain description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public WSDomain hitCount(Long hitCount) {
    
    this.hitCount = hitCount;
    return this;
  }

   /**
   * Get hitCount
   * @return hitCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getHitCount() {
    return hitCount;
  }


  public void setHitCount(Long hitCount) {
    this.hitCount = hitCount;
  }


  public WSDomain indexInfos(List<WSIndexInfo> indexInfos) {
    
    this.indexInfos = indexInfos;
    return this;
  }

  public WSDomain addIndexInfosItem(WSIndexInfo indexInfosItem) {
    if (this.indexInfos == null) {
      this.indexInfos = new ArrayList<WSIndexInfo>();
    }
    this.indexInfos.add(indexInfosItem);
    return this;
  }

   /**
   * Get indexInfos
   * @return indexInfos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WSIndexInfo> getIndexInfos() {
    return indexInfos;
  }


  public void setIndexInfos(List<WSIndexInfo> indexInfos) {
    this.indexInfos = indexInfos;
  }


  public WSDomain fieldInfos(List<WSFieldInfo> fieldInfos) {
    
    this.fieldInfos = fieldInfos;
    return this;
  }

  public WSDomain addFieldInfosItem(WSFieldInfo fieldInfosItem) {
    if (this.fieldInfos == null) {
      this.fieldInfos = new ArrayList<WSFieldInfo>();
    }
    this.fieldInfos.add(fieldInfosItem);
    return this;
  }

   /**
   * Get fieldInfos
   * @return fieldInfos
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WSFieldInfo> getFieldInfos() {
    return fieldInfos;
  }


  public void setFieldInfos(List<WSFieldInfo> fieldInfos) {
    this.fieldInfos = fieldInfos;
  }


  public WSDomain subdomains(List<WSDomain> subdomains) {
    
    this.subdomains = subdomains;
    return this;
  }

  public WSDomain addSubdomainsItem(WSDomain subdomainsItem) {
    if (this.subdomains == null) {
      this.subdomains = new ArrayList<WSDomain>();
    }
    this.subdomains.add(subdomainsItem);
    return this;
  }

   /**
   * Get subdomains
   * @return subdomains
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WSDomain> getSubdomains() {
    return subdomains;
  }


  public void setSubdomains(List<WSDomain> subdomains) {
    this.subdomains = subdomains;
  }


  public WSDomain referenceEntryCount(Long referenceEntryCount) {
    
    this.referenceEntryCount = referenceEntryCount;
    return this;
  }

   /**
   * Get referenceEntryCount
   * @return referenceEntryCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getReferenceEntryCount() {
    return referenceEntryCount;
  }


  public void setReferenceEntryCount(Long referenceEntryCount) {
    this.referenceEntryCount = referenceEntryCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WSDomain wsDomain = (WSDomain) o;
    return Objects.equals(this.id, wsDomain.id) &&
        Objects.equals(this.name, wsDomain.name) &&
        Objects.equals(this.description, wsDomain.description) &&
        Objects.equals(this.hitCount, wsDomain.hitCount) &&
        Objects.equals(this.indexInfos, wsDomain.indexInfos) &&
        Objects.equals(this.fieldInfos, wsDomain.fieldInfos) &&
        Objects.equals(this.subdomains, wsDomain.subdomains) &&
        Objects.equals(this.referenceEntryCount, wsDomain.referenceEntryCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, hitCount, indexInfos, fieldInfos, subdomains, referenceEntryCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WSDomain {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    hitCount: ").append(toIndentedString(hitCount)).append("\n");
    sb.append("    indexInfos: ").append(toIndentedString(indexInfos)).append("\n");
    sb.append("    fieldInfos: ").append(toIndentedString(fieldInfos)).append("\n");
    sb.append("    subdomains: ").append(toIndentedString(subdomains)).append("\n");
    sb.append("    referenceEntryCount: ").append(toIndentedString(referenceEntryCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

