/*
 * The EBI Search: RESTful Web services
 * This is an API documentation for [EBI Search](https://www.ebi.ac.uk/ebisearch) RESTful Web services.
 *
 * The version of the OpenAPI document: all
 * Contact: www-prod@ebi.ac.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.dissco.digitisers.clients.ebi.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import eu.dissco.digitisers.clients.ebi.openapi.model.WSSequenceToolResultsOutputFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WSSequenceToolReader
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T16:03:02.863Z[GMT]")
public class WSSequenceToolReader {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_RESULTS_OUTPUT_FORMATS = "resultsOutputFormats";
  @SerializedName(SERIALIZED_NAME_RESULTS_OUTPUT_FORMATS)
  private List<WSSequenceToolResultsOutputFormat> resultsOutputFormats = null;


  public WSSequenceToolReader id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public WSSequenceToolReader description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public WSSequenceToolReader resultsOutputFormats(List<WSSequenceToolResultsOutputFormat> resultsOutputFormats) {
    
    this.resultsOutputFormats = resultsOutputFormats;
    return this;
  }

  public WSSequenceToolReader addResultsOutputFormatsItem(WSSequenceToolResultsOutputFormat resultsOutputFormatsItem) {
    if (this.resultsOutputFormats == null) {
      this.resultsOutputFormats = new ArrayList<WSSequenceToolResultsOutputFormat>();
    }
    this.resultsOutputFormats.add(resultsOutputFormatsItem);
    return this;
  }

   /**
   * Get resultsOutputFormats
   * @return resultsOutputFormats
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WSSequenceToolResultsOutputFormat> getResultsOutputFormats() {
    return resultsOutputFormats;
  }


  public void setResultsOutputFormats(List<WSSequenceToolResultsOutputFormat> resultsOutputFormats) {
    this.resultsOutputFormats = resultsOutputFormats;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WSSequenceToolReader wsSequenceToolReader = (WSSequenceToolReader) o;
    return Objects.equals(this.id, wsSequenceToolReader.id) &&
        Objects.equals(this.description, wsSequenceToolReader.description) &&
        Objects.equals(this.resultsOutputFormats, wsSequenceToolReader.resultsOutputFormats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, description, resultsOutputFormats);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WSSequenceToolReader {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    resultsOutputFormats: ").append(toIndentedString(resultsOutputFormats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

