/*
 * The EBI Search: RESTful Web services
 * This is an API documentation for [EBI Search](https://www.ebi.ac.uk/ebisearch) RESTful Web services.
 *
 * The version of the OpenAPI document: all
 * Contact: www-prod@ebi.ac.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.dissco.digitisers.clients.ebi.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import eu.dissco.digitisers.clients.ebi.openapi.model.WSDomain;
import eu.dissco.digitisers.clients.ebi.openapi.model.WSEntry;
import eu.dissco.digitisers.clients.ebi.openapi.model.WSFacet;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WSSearchResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T16:03:02.863Z[GMT]")
public class WSSearchResult {
  public static final String SERIALIZED_NAME_HIT_COUNT = "hitCount";
  @SerializedName(SERIALIZED_NAME_HIT_COUNT)
  private Long hitCount;

  public static final String SERIALIZED_NAME_ENTRIES = "entries";
  @SerializedName(SERIALIZED_NAME_ENTRIES)
  private List<WSEntry> entries = null;

  public static final String SERIALIZED_NAME_FACETS = "facets";
  @SerializedName(SERIALIZED_NAME_FACETS)
  private List<WSFacet> facets = null;

  public static final String SERIALIZED_NAME_DOMAINS = "domains";
  @SerializedName(SERIALIZED_NAME_DOMAINS)
  private List<WSDomain> domains = null;

  public static final String SERIALIZED_NAME_FEEDTITLE = "feedtitle";
  @SerializedName(SERIALIZED_NAME_FEEDTITLE)
  private String feedtitle;

  public static final String SERIALIZED_NAME_REQUESTED_DOMAIN_ID = "requestedDomainId";
  @SerializedName(SERIALIZED_NAME_REQUESTED_DOMAIN_ID)
  private String requestedDomainId;

  public static final String SERIALIZED_NAME_QUERY_STRING = "queryString";
  @SerializedName(SERIALIZED_NAME_QUERY_STRING)
  private String queryString;

  public static final String SERIALIZED_NAME_CACHE = "cache";
  @SerializedName(SERIALIZED_NAME_CACHE)
  private Boolean cache;

  public static final String SERIALIZED_NAME_SELECTED_FACET_VALUES = "selectedFacetValues";
  @SerializedName(SERIALIZED_NAME_SELECTED_FACET_VALUES)
  private List<String> selectedFacetValues = null;

  public static final String SERIALIZED_NAME_ENTRYSIZE = "entrysize";
  @SerializedName(SERIALIZED_NAME_ENTRYSIZE)
  private Integer entrysize;


  public WSSearchResult hitCount(Long hitCount) {
    
    this.hitCount = hitCount;
    return this;
  }

   /**
   * Get hitCount
   * @return hitCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getHitCount() {
    return hitCount;
  }


  public void setHitCount(Long hitCount) {
    this.hitCount = hitCount;
  }


  public WSSearchResult entries(List<WSEntry> entries) {
    
    this.entries = entries;
    return this;
  }

  public WSSearchResult addEntriesItem(WSEntry entriesItem) {
    if (this.entries == null) {
      this.entries = new ArrayList<WSEntry>();
    }
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WSEntry> getEntries() {
    return entries;
  }


  public void setEntries(List<WSEntry> entries) {
    this.entries = entries;
  }


  public WSSearchResult facets(List<WSFacet> facets) {
    
    this.facets = facets;
    return this;
  }

  public WSSearchResult addFacetsItem(WSFacet facetsItem) {
    if (this.facets == null) {
      this.facets = new ArrayList<WSFacet>();
    }
    this.facets.add(facetsItem);
    return this;
  }

   /**
   * Get facets
   * @return facets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WSFacet> getFacets() {
    return facets;
  }


  public void setFacets(List<WSFacet> facets) {
    this.facets = facets;
  }


  public WSSearchResult domains(List<WSDomain> domains) {
    
    this.domains = domains;
    return this;
  }

  public WSSearchResult addDomainsItem(WSDomain domainsItem) {
    if (this.domains == null) {
      this.domains = new ArrayList<WSDomain>();
    }
    this.domains.add(domainsItem);
    return this;
  }

   /**
   * Get domains
   * @return domains
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WSDomain> getDomains() {
    return domains;
  }


  public void setDomains(List<WSDomain> domains) {
    this.domains = domains;
  }


  public WSSearchResult feedtitle(String feedtitle) {
    
    this.feedtitle = feedtitle;
    return this;
  }

   /**
   * Get feedtitle
   * @return feedtitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFeedtitle() {
    return feedtitle;
  }


  public void setFeedtitle(String feedtitle) {
    this.feedtitle = feedtitle;
  }


  public WSSearchResult requestedDomainId(String requestedDomainId) {
    
    this.requestedDomainId = requestedDomainId;
    return this;
  }

   /**
   * Get requestedDomainId
   * @return requestedDomainId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRequestedDomainId() {
    return requestedDomainId;
  }


  public void setRequestedDomainId(String requestedDomainId) {
    this.requestedDomainId = requestedDomainId;
  }


  public WSSearchResult queryString(String queryString) {
    
    this.queryString = queryString;
    return this;
  }

   /**
   * Get queryString
   * @return queryString
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getQueryString() {
    return queryString;
  }


  public void setQueryString(String queryString) {
    this.queryString = queryString;
  }


  public WSSearchResult cache(Boolean cache) {
    
    this.cache = cache;
    return this;
  }

   /**
   * Get cache
   * @return cache
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getCache() {
    return cache;
  }


  public void setCache(Boolean cache) {
    this.cache = cache;
  }


  public WSSearchResult selectedFacetValues(List<String> selectedFacetValues) {
    
    this.selectedFacetValues = selectedFacetValues;
    return this;
  }

  public WSSearchResult addSelectedFacetValuesItem(String selectedFacetValuesItem) {
    if (this.selectedFacetValues == null) {
      this.selectedFacetValues = new ArrayList<String>();
    }
    this.selectedFacetValues.add(selectedFacetValuesItem);
    return this;
  }

   /**
   * Get selectedFacetValues
   * @return selectedFacetValues
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getSelectedFacetValues() {
    return selectedFacetValues;
  }


  public void setSelectedFacetValues(List<String> selectedFacetValues) {
    this.selectedFacetValues = selectedFacetValues;
  }


  public WSSearchResult entrysize(Integer entrysize) {
    
    this.entrysize = entrysize;
    return this;
  }

   /**
   * Get entrysize
   * @return entrysize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getEntrysize() {
    return entrysize;
  }


  public void setEntrysize(Integer entrysize) {
    this.entrysize = entrysize;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WSSearchResult wsSearchResult = (WSSearchResult) o;
    return Objects.equals(this.hitCount, wsSearchResult.hitCount) &&
        Objects.equals(this.entries, wsSearchResult.entries) &&
        Objects.equals(this.facets, wsSearchResult.facets) &&
        Objects.equals(this.domains, wsSearchResult.domains) &&
        Objects.equals(this.feedtitle, wsSearchResult.feedtitle) &&
        Objects.equals(this.requestedDomainId, wsSearchResult.requestedDomainId) &&
        Objects.equals(this.queryString, wsSearchResult.queryString) &&
        Objects.equals(this.cache, wsSearchResult.cache) &&
        Objects.equals(this.selectedFacetValues, wsSearchResult.selectedFacetValues) &&
        Objects.equals(this.entrysize, wsSearchResult.entrysize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hitCount, entries, facets, domains, feedtitle, requestedDomainId, queryString, cache, selectedFacetValues, entrysize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WSSearchResult {\n");
    sb.append("    hitCount: ").append(toIndentedString(hitCount)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    facets: ").append(toIndentedString(facets)).append("\n");
    sb.append("    domains: ").append(toIndentedString(domains)).append("\n");
    sb.append("    feedtitle: ").append(toIndentedString(feedtitle)).append("\n");
    sb.append("    requestedDomainId: ").append(toIndentedString(requestedDomainId)).append("\n");
    sb.append("    queryString: ").append(toIndentedString(queryString)).append("\n");
    sb.append("    cache: ").append(toIndentedString(cache)).append("\n");
    sb.append("    selectedFacetValues: ").append(toIndentedString(selectedFacetValues)).append("\n");
    sb.append("    entrysize: ").append(toIndentedString(entrysize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

