/*
 * The EBI Search: RESTful Web services
 * This is an API documentation for [EBI Search](https://www.ebi.ac.uk/ebisearch) RESTful Web services.
 *
 * The version of the OpenAPI document: all
 * Contact: www-prod@ebi.ac.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.dissco.digitisers.clients.ebi.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import eu.dissco.digitisers.clients.ebi.openapi.model.WSSequenceToolReader;
import eu.dissco.digitisers.clients.ebi.openapi.model.WSValueMapper;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WSSeqToolsHelp
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T16:03:02.863Z[GMT]")
public class WSSeqToolsHelp {
  public static final String SERIALIZED_NAME_VALUE_MAPPERS = "valueMappers";
  @SerializedName(SERIALIZED_NAME_VALUE_MAPPERS)
  private List<WSValueMapper> valueMappers = null;

  public static final String SERIALIZED_NAME_SEQUENCE_TOOL_READERS = "sequenceToolReaders";
  @SerializedName(SERIALIZED_NAME_SEQUENCE_TOOL_READERS)
  private List<WSSequenceToolReader> sequenceToolReaders = null;


  public WSSeqToolsHelp valueMappers(List<WSValueMapper> valueMappers) {
    
    this.valueMappers = valueMappers;
    return this;
  }

  public WSSeqToolsHelp addValueMappersItem(WSValueMapper valueMappersItem) {
    if (this.valueMappers == null) {
      this.valueMappers = new ArrayList<WSValueMapper>();
    }
    this.valueMappers.add(valueMappersItem);
    return this;
  }

   /**
   * Get valueMappers
   * @return valueMappers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WSValueMapper> getValueMappers() {
    return valueMappers;
  }


  public void setValueMappers(List<WSValueMapper> valueMappers) {
    this.valueMappers = valueMappers;
  }


  public WSSeqToolsHelp sequenceToolReaders(List<WSSequenceToolReader> sequenceToolReaders) {
    
    this.sequenceToolReaders = sequenceToolReaders;
    return this;
  }

  public WSSeqToolsHelp addSequenceToolReadersItem(WSSequenceToolReader sequenceToolReadersItem) {
    if (this.sequenceToolReaders == null) {
      this.sequenceToolReaders = new ArrayList<WSSequenceToolReader>();
    }
    this.sequenceToolReaders.add(sequenceToolReadersItem);
    return this;
  }

   /**
   * Get sequenceToolReaders
   * @return sequenceToolReaders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WSSequenceToolReader> getSequenceToolReaders() {
    return sequenceToolReaders;
  }


  public void setSequenceToolReaders(List<WSSequenceToolReader> sequenceToolReaders) {
    this.sequenceToolReaders = sequenceToolReaders;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WSSeqToolsHelp wsSeqToolsHelp = (WSSeqToolsHelp) o;
    return Objects.equals(this.valueMappers, wsSeqToolsHelp.valueMappers) &&
        Objects.equals(this.sequenceToolReaders, wsSeqToolsHelp.sequenceToolReaders);
  }

  @Override
  public int hashCode() {
    return Objects.hash(valueMappers, sequenceToolReaders);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WSSeqToolsHelp {\n");
    sb.append("    valueMappers: ").append(toIndentedString(valueMappers)).append("\n");
    sb.append("    sequenceToolReaders: ").append(toIndentedString(sequenceToolReaders)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

