/*
 * The EBI Search: RESTful Web services
 * This is an API documentation for [EBI Search](https://www.ebi.ac.uk/ebisearch) RESTful Web services.
 *
 * The version of the OpenAPI document: all
 * Contact: www-prod@ebi.ac.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.dissco.digitisers.clients.ebi.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WSTermStats
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T16:03:02.863Z[GMT]")
public class WSTermStats {
  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  private String text;

  public static final String SERIALIZED_NAME_DOC_FREQ = "docFreq";
  @SerializedName(SERIALIZED_NAME_DOC_FREQ)
  private Integer docFreq;


  public WSTermStats text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getText() {
    return text;
  }


  public void setText(String text) {
    this.text = text;
  }


  public WSTermStats docFreq(Integer docFreq) {
    
    this.docFreq = docFreq;
    return this;
  }

   /**
   * Get docFreq
   * @return docFreq
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getDocFreq() {
    return docFreq;
  }


  public void setDocFreq(Integer docFreq) {
    this.docFreq = docFreq;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WSTermStats wsTermStats = (WSTermStats) o;
    return Objects.equals(this.text, wsTermStats.text) &&
        Objects.equals(this.docFreq, wsTermStats.docFreq);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, docFreq);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WSTermStats {\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    docFreq: ").append(toIndentedString(docFreq)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

