/*
 * The EBI Search: RESTful Web services
 * This is an API documentation for [EBI Search](https://www.ebi.ac.uk/ebisearch) RESTful Web services.
 *
 * The version of the OpenAPI document: all
 * Contact: www-prod@ebi.ac.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package eu.dissco.digitisers.clients.ebi.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import eu.dissco.digitisers.clients.ebi.openapi.model.WSTermStats;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WSTopTermsResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-01T16:03:02.863Z[GMT]")
public class WSTopTermsResult {
  public static final String SERIALIZED_NAME_TOTAL_TERM_COUNT = "totalTermCount";
  @SerializedName(SERIALIZED_NAME_TOTAL_TERM_COUNT)
  private Long totalTermCount;

  public static final String SERIALIZED_NAME_TOP_TERMS = "topTerms";
  @SerializedName(SERIALIZED_NAME_TOP_TERMS)
  private List<WSTermStats> topTerms = null;


  public WSTopTermsResult totalTermCount(Long totalTermCount) {
    
    this.totalTermCount = totalTermCount;
    return this;
  }

   /**
   * Get totalTermCount
   * @return totalTermCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getTotalTermCount() {
    return totalTermCount;
  }


  public void setTotalTermCount(Long totalTermCount) {
    this.totalTermCount = totalTermCount;
  }


  public WSTopTermsResult topTerms(List<WSTermStats> topTerms) {
    
    this.topTerms = topTerms;
    return this;
  }

  public WSTopTermsResult addTopTermsItem(WSTermStats topTermsItem) {
    if (this.topTerms == null) {
      this.topTerms = new ArrayList<WSTermStats>();
    }
    this.topTerms.add(topTermsItem);
    return this;
  }

   /**
   * Get topTerms
   * @return topTerms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<WSTermStats> getTopTerms() {
    return topTerms;
  }


  public void setTopTerms(List<WSTermStats> topTerms) {
    this.topTerms = topTerms;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WSTopTermsResult wsTopTermsResult = (WSTopTermsResult) o;
    return Objects.equals(this.totalTermCount, wsTopTermsResult.totalTermCount) &&
        Objects.equals(this.topTerms, wsTopTermsResult.topTerms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalTermCount, topTerms);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WSTopTermsResult {\n");
    sb.append("    totalTermCount: ").append(toIndentedString(totalTermCount)).append("\n");
    sb.append("    topTerms: ").append(toIndentedString(topTerms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

